### PR TITLE
Hacky way to allow plugin to upload to Happening

### PR DESCRIPTION
**Pull request by Dougley**
The plugin can't upload to Happening using the `Util` requirement from my experience, removing this along with `winnerString` allows the plugin to be uploaded.
This may break having multiple winners, but it does the job without breaking the plugin's functionality.

### CODE REVIEW

**Comment by Dougley** [comment]
Just tested, removing these requirements and strings doesn't break having multiple winners.

**Comment by lesteenman** [comment]
Really? What problems are you experiencing with it? I'm having no issues whatsoever uploading it with the Util.common. It's just a good way of splitting generic utility functions or functions that are used both by the Server and Client from their respective files. In this case, it prevents code duplication.

**Comment by lesteenman** [comment]
By the way, in your commit, notifications will not show who won the round, since you removed that parameter from the string ;)

**Comment by Dougley** [comment]
Ah, stupid of me to oversee that. :stuck_out_tongue_winking_eye:
But for the errors, powershell and terminal (Ubuntu 14.10) throw;

```
Error 400 (Illegal request.)

noSuchLib(util)
Error
    at Error.PluginError (backend/v8boot.js:24:16)
    at handleCommand (backend/v8boot.js:115:10)
    at request (backend/v8boot.js:219:9)
    at require (backend/v8boot.js:54:33)
    at eval (/file/server@17124w@17291:8:3)
    at eval (/file/server@17124w@17291:244:11952)
    at require (backend/v8boot.js:59:3)
    at handleCommand (backend/v8boot.js:122:15)
    at backend/v8boot.js:223:2
```

I said that it was a hacky method, I don't know CoffeeCode all that well.

**Comment by lesteenman** [comment]
That's weird... You say it happens with your other upload method as well?

What's helped for me before, not sure if it matters, is to first upload everything without the requires, so that the Util.common.coffee and the server.coffee files are already uploaded, and then upload a version that actually requires those. Please let me know if that's the issue so we can fix that :)

As for coffeescript: It's basically just javascript, and I can really recommend to either keep a compiler opened while working, or to add a compiler to your editor. Makes it really easy to see what the equivalent in Javascript is!

**Comment by Dougley** [comment]
Even without the requires, the files won't upload unless I do my method from above, but you mentioned Util.common.coffee, which isn't included in this repo, maybe that's the case, I don't really know :P

**Comment by lesteenman** [comment]
Ah, yikes, thats my bad. I forgot adding that to Git. I'll do so tomorrow,
but for now you can just add a placeholder method that returns blank or
something.

**Comment by Dougley** [comment]
Pushed a placeholder fix, this fixes the problems

**Comment by lesteenman** [comment]
I pushed the file, the newest version should work normally. Please reopen if it doesn't.

**Pull request closed without merging**
